### ISSUE TITLE
port-request: net-im/signal-desktop

### ISSUE THREAD

**Issue by ehaupt** [tagattie/FreeBSD-Electron#119]
In light of the recent [backlash](https://www.bbc.com/news/technology-55634139) following WhatsApp's updated _Privacy Terms_ it would be very useful to have a FreeBSD port for the [Signal Desktop](https://github.com/signalapp/Signal-Desktop) using electron8.

**Comment by tagattie** [comment]
Interesting. I will see what I can do for the port.

**Comment by tagattie** [comment]
I have managed to get the initial window (with the Signal icon) come up but it gets stuck there. It appears Signal Desktop depends on some binary blobs only available for Linux, Mac, and Windows though I don't know if the dependency is the cause of stuck. So far little luck...

**Comment by ehaupt** [comment]
Thank you for trying.

**Comment by MikaelUrankar** [comment]
I have some work in progress: text messaging is working and videocall almost work (the mic doesn't work for some reason). [https://github.com/MikaelUrankar/signal-desktop](https://github.com/MikaelUrankar/signal-desktop).
One major issue is this error (I used a crude hack to get past this):
```
error: Error: ENOTTY: inappropriate ioctl for device, uv_pipe_open
   at new Socket (net.js:329:26)
   at createWritableStdioStream (internal/bootstrap/switches/is_main_thread.js:67:18)
   at process.getStdout [as stdout] (internal/bootstrap/switches/is_main_thread.js:122:12)
   at IncomingMessage.Readable.pipe (_stream_readable.js:659:32)
   at ClientRequest.<anonymous> ([REDACTED]/Signal-Desktop-1.40.1/node_modules/node-fetch/lib/index.js:1553:19)
   at ClientRequest.emit (events.js:315:20)
   at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
   at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
   at TLSSocket.socketOnData (_http_client.js:469:22)
   at TLSSocket.emit (events.js:315:20)","v":0}```

**Comment by MikaelUrankar** [comment]
This is now available in the FreeBSD ports tree.

**Comment by ehaupt** [comment]
> This is now available in the FreeBSD ports tree.

I saw! Thank you for porting it.
